/**
 * D33 / FR-11 — generates `dist/sw.js`.
 *
 * Generated rather than committed for the same reason the manifest is: the
 * precache list is the build's own hashed asset names, and a hand-written copy
 * of those is wrong the moment anything changes. Written by hand rather than by
 * Workbox because §5.3 keeps the dependency list short and the whole worker is
 * ninety lines — most of a PWA toolchain is for problems a static, versioned,
 * eight-route site does not have.
 *
 * **The rule this implements is one sentence (D33): you can look offline, you
 * cannot change anything offline.** An offline write would have to be queued
 * and replayed, and a queue of writes replayed later is exactly the two-way
 * merge D6 exists to prevent.
 */
import { readFile, readdir, writeFile } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const dist = join(root, 'dist')

async function main() {
  const shell = await readFile(join(dist, 'index.html'), 'utf8')

  /**
   * Only what the first paint needs. Every route's JavaScript is a lazy chunk
   * (§12) and is cached on first use instead — precaching all of them would
   * make an install download the whole site to look at one watch.
   *
   * **Both tag shapes, and missing the second one breaks the whole feature.**
   * Vite emits the entry as `<script src>` and every chunk the entry imports
   * statically — D40 pins React into one — as `<link rel="modulepreload">`. A
   * reader that only understands `src=` precaches an entry that cannot run:
   * online nobody notices, because the modulepreload is fetched normally, and
   * offline the app fails to boot with an install that reported success.
   */
  const entryScripts = [
    ...[...shell.matchAll(/src="(\/assets\/[^"]+\.js)"/g)].map((m) => m[1]),
    ...[...shell.matchAll(/<link[^>]+modulepreload[^>]+href="(\/assets\/[^"]+\.js)"/g)].map(
      (m) => m[1],
    ),
    ...[...shell.matchAll(/<link[^>]+href="(\/assets\/[^"]+\.js)"[^>]+modulepreload/g)].map(
      (m) => m[1],
    ),
  ]
  const entryStyles = [...shell.matchAll(/href="(\/assets\/[^"]+\.css)"/g)].map((m) => m[1])

  if (entryScripts.length === 0) {
    throw new Error('sw: found no entry scripts in dist/index.html — the tag shape has changed')
  }

  const fonts = (await readdir(join(dist, 'assets')))
    .filter((name) => name.endsWith('.woff2'))
    .map((name) => `/assets/${name}`)

  const catalog = await readFile(join(dist, 'catalog/catalog.json'), 'utf8')
  const version = createHash('sha256')
    .update(shell + entryScripts.join() + catalog)
    .digest('hex')
    .slice(0, 12)

  const precache = [
    '/',
    ...entryScripts,
    ...entryStyles,
    ...fonts,
    '/catalog/catalog.json',
    '/manifest.webmanifest',
    '/favicon.svg',
    '/icon-192.png',
  ]

  const sw = `/* Generated by scripts/sw.ts — do not edit. Build ${version}. */
const VERSION = ${JSON.stringify(version)}
const SHELL = 'cc-shell-' + VERSION
const RUNTIME = 'cc-runtime-' + VERSION
const PRECACHE = ${JSON.stringify(precache, null, 2)}

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(SHELL).then((cache) => cache.addAll(PRECACHE)))
  // NO skipWaiting here, deliberately. A worker that activates the moment it
  // installs swaps the code under a page that is already running, and the user
  // did not ask for that. FR-11.2's "Update available" prompt is what asks.
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((key) => !key.endsWith(VERSION)).map((key) => caches.delete(key))),
      )
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('message', (event) => {
  if (event.data === 'SKIP_WAITING') self.skipWaiting()

  // FR-11.6 — signing out purges EVERY cache. A shared device must not hold the
  // last person's watches, and "every" includes the shell: it is cheap to
  // refetch and leaving one cache behind is how the rule stops being true.
  if (event.data === 'PURGE') {
    event.waitUntil(caches.keys().then((keys) => Promise.all(keys.map((k) => caches.delete(k)))))
  }
})

self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET') return

  const url = new URL(request.url)

  // FR-11.3 — everything that is not ours is network-only, which is Supabase.
  // Nothing about a session or a collection is ever served from here. What
  // makes the collection readable offline (FR-11.4) is the app keeping its own
  // last-known copy and saying so, not this cache quietly answering for a
  // server that is unreachable.
  if (url.origin !== self.location.origin) return

  // A navigation gets the shell. The app is a single page; which route it
  // renders is the router's business and the shell is the same file for all of
  // them, including the prerendered ones the SEO step writes.
  if (request.mode === 'navigate') {
    event.respondWith(
      caches.match('/').then((cached) => {
        const network = fetch(request).catch(() => cached)
        return cached ?? network
      }),
    )
    return
  }

  // Hashed assets, the catalogue and images are immutable behind a version, so
  // cache-first is a rule rather than an invalidation problem (FR-11.2).
  const immutable =
    url.pathname.startsWith('/assets/') ||
    url.pathname.startsWith('/img/') ||
    url.pathname.startsWith('/catalog/')

  if (immutable) {
    event.respondWith(
      caches.match(request).then(
        (cached) =>
          cached ??
          fetch(request).then((response) => {
            if (response.ok) {
              const copy = response.clone()
              void caches.open(RUNTIME).then((cache) => cache.put(request, copy))
            }
            return response
          }),
      ),
    )
  }
})
`

  await writeFile(join(dist, 'sw.js'), sw, 'utf8')
  console.log(`sw: dist/sw.js at ${version}, ${precache.length} files precached`)
}

await main()
